import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";  
import Footer from "./components/Footer";  
import { StateContext } from "@/context/StateContext"; // FIXED: Import StateProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rogers Devices Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StateContext>  {/* FIXED: Wrap the app with StateProvider */}
          {/* Navbar */}
          <header>
            <Navbar />
          </header>
      
          {/* Main Content */}
          <main className="main-container">
            <Toaster />
            {children}
          </main>

          {/* Footer */}
          <footer>
            <Footer />
          </footer>
        </StateContext>
      </body>
    </html>
  );
}
